// boilerplate/renderer/Link.vue
<template>
  <a :class="{ active: pageContext.urlPathname === $attrs.href }">
    <slot />
  </a>
</template>
<style scoped>
a {
  padding: 3px 10px;
}
a.active {
  background-color: #eee;
}
</style>
<script lang="ts" setup>
import { usePageContext } from './usePageContextVue'
const pageContext = usePageContext()
</script>

// packages/boilerplate/templates/preact/renderer/Link.tsx
import { usePageContext } from './usePageContext'
import type { ComponentChildren } from 'preact'

export { Link }

function Link(props: { href?: string; className?: string; children: ComponentChildren }) {
  const pageContext = usePageContext()
  const className = [props.className, pageContext.urlPathname === props.href && 'is-active'].filter(Boolean).join(' ')
  return <a {...props} className={className} />
}
